apiVersion: v1
data:
  logstash.conf: |-
    input {
      file {
        path => "/logs/app.log"  # Path to the log file inside the Logstash container
        start_position => "beginning"  # Read logs from the beginning
        sincedb_path => "/dev/null"   # Prevent Logstash from persisting state between restarts
      }
    }

    filter {
      grok {
        match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} \[%{DATA:thread}\] %{LOGLEVEL:log_level}  %{JAVACLASS:class} - %{GREEDYDATA:message}" }
      }
      date {
        match => ["timestamp", "yyyy-MM-dd HH:mm:ss"]
        target => "@timestamp"
      }
    }

    output {
      elasticsearch {
        hosts => ["elasticsearch:9200"]
        index => "ticketresolver-logs-%{+YYYY.MM.dd}"
      }
      stdout {
        codec => rubydebug
      }
    }
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: logstash
  name: logstash-cm0
